export const locators = {
    chatPage: {
        chatTextArea: '[placeholder:"Send a message…"]',
        mainStatChatBtn: 'button.header-chat__button',
        chatSearchField: '[placeholder:"Search"]',
        createChatBtn: 'button.chat-modal__button',
        chatValidationError: 'p.chat-input-area__error',
        contextMenu: 'div.context-menu',
        blockUserBtn: '//span[contains(text(,"Block User"]/..',
        confirmModal: 'button.confirm-modal__buttons--first',
        contactSupportBtn: '[rel:"noreferrer noopener"]',
        messageTimeIcon: 'span.message-time',
        translateIcon: 'svg.message__translate-icon',
        startChatWithFirstSuggestedUser: '.chat-modal__card button',
        chatTextArea2: 'div.chat-input-area__textarea',
        atachmentBtn: '.chat-input-area__attach-btn',
        mediaMessage: 'div.chat-private-message-file__content',
        emojiBtn: 'button.chat-input-area__button-emoji-picker',
    },
}
